server:
  port: 8000

spring:
  application:
    name: guli_teacher
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: hth123456
    username: root

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

